### ISSUE TITLE
Make archiver more robust to unexpected failures

### ISSUE THREAD

**Issue by ljgray** [chime-experiment/comet#102]
@ljgray Longer term it's probably more robust to do something like this:
- Add an extra list for states being processed (probably should end up with at most one entry in it)
- Have the main loop first process states in this list (i.e. add them to the database). One the state is processed successfully use LREM to remove it from the processing list.
- After this has been done have the main loop use BLMOVE to wait for a new list item and move it to the processing list in a single call.

That should be robust to connection failures both for MySQL and Redis.

_Originally posted by @jrs65 in https://github.com/chime-experiment/comet/issues/101#issuecomment-1635431925_

**Comment by ketiltrout** [comment]
A simpler algorithm might be:
 * Don't remove states from redis while archiving them.
 * If, later (i.e. in a future iteration through redis), you find a state in redis that is _already_ archived, then delete it from redis.

**Comment by jrs65** [comment]
It would probably also make sense for it to proactively add the states and datasets it depends on into the DB, i.e. check if the base dataset is in the DB already and if not push it onto the *start* of the redis list of datasets to add, then continue (such that it is processed next time around).
